# Generated by Django 4.0.5 on 2022-06-16 12:33

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_post_comments_post_commented_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_likes',
            field=models.ManyToManyField(related_name='comments_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
