# Generated by Django 4.0.5 on 2022-06-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_starting_bid_auction_listing_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='bid',
            new_name='starting_bid',
        ),
    ]
