# Generated by Django 4.0.5 on 2022-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bid_auction_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
