# Generated by Django 4.0.5 on 2022-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Smart Devices', 'Smart Devices'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Books', 'Books'), ('Fragrance', 'Fragrance'), ('Furniture', 'Furniture'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
